### ISSUE TITLE
Why i can't use this ?

### ISSUE THREAD

**Issue by zeing** [chmjs/vuetify-colorizer#3]
when click in component ![image](https://user-images.githubusercontent.com/20161393/44666258-31828180-aa42-11e8-8d51-dcfc090c0619.png)

**Comment by manico** [comment]
Could you show us code how are you initialising component? Is there any error in console?

**Comment by zeing** [comment]
It don’t have error in console , if code example is ready i will reply again
On 28 Aug 2561 20:44 +0700, Jadranko Dragoje <notifications@github.com>, wrote:

Could you show us code how are you initialising component? Is there any error in console?

**Comment by zeing** [comment]
excuse me , Where i take reproduction template for vuetify-colorizer

**Comment by manico** [comment]
You can just give us url of your repo or create new repo where you use this component. If you run `npm run serve` locally in vuetify-colorizer project, can you see material pallete?

**Comment by ssendev** [comment]
I had the same issue and the problem is that the usage info dosn't mention that `import '@nsoft/vuetify-colorizer/dist/vuetify-colorizer.css'` is required to get the necessary css.

**Comment by manico** [comment]
> I had the same issue and the problem is that the usage info dosn't mention that `import '@nsoft/vuetify-colorizer/dist/vuetify-colorizer.css'` is required to get the necessary css.

You are right. Will update README. :)
